baseURL: https://jino-rohit.github.io/jino_rohit/
languageCode: en-us
title: Jino Rohit
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Jino Rohit"
  description: "ML Engineer"
  keywords: [Blog, Portfolio, PaperMod]
  # author: "Me"
  # author: ["Me", "You"] # multiple authors
  # images: ["/icon.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  social: true

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  enableLatex: true

  label:
    text: "Jino Rohit"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Jino Rohit"
    subtitle: "ML Engineer"
    imageUrl: "img/jino.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: jino
    buttons: []

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: email
      url: "mailto:find.jinorohit@gmail.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/jino-rohit-6032541b5/"
    - name: twitter
      url: "https://x.com/jino_rohit"
    - name: github
      url: "https://github.com/JINO-ROHIT"

  analytics:
    # google:
    #   SiteVerificationTag: "G-W6HV8VE5SV"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    # URL: "https://github.com/<path_to_repo>/content"
    # Text: "Suggest Changes" # edit text
    # appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight: 10
    - identifier: project
      name: project
      url: /project/
      weight: 20
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 40
    - identifier: experience
      name: experience
      url: /experience/
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
markdown: kramdown